name: Build and Deploy

on:
  push:
    branches: [ main ]  # 변경 사항을 푸시할 때마다 실행
  pull_request:
    branches: [ main ]  # Pull Request가 생성될 때마다 실행

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_PEM_KEY }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
            su
            ${{ secrets.SERVER_PASSWORD }}
            cd ${{ secrets.SERVER_TARGET }}
            git pull
            npm install
            npm run build
            pm2 reload quizmon-fe
